# -*- coding: utf-8 -*-
"""
Project Euler - Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten 
    pentagonal numbers are:
        1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
    70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, whose sum and difference are 
    pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

# Imports
import time

# Global variables

# Lamda functions
pent = lambda n: (n*(3*n-1))/2

# Functions

# Main functions
def main():
    for i in range(1,10):
        print(i, pent(i))
    
    print('Output') 

# Execute code
start = time.time()
if __name__ == "__main__":
    main()
end = time.time()
print('Run time: {}'.format(end - start))    
